/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF("/Random_Lego_Bricks.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 2.3982, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: "Random_Lego_Bricks" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_01.geometry}
          material={materials.Plastic_Yellow}
          position={[0.8843, -2.6283, 2.4765]}
          rotation={[0.1852, -0.8695, 0.2415]}
          userData={{ name: "detail_01" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_02.geometry}
          material={materials.Plastic_Blue}
          position={[2.8026, 0.3726, 1.6037]}
          rotation={[-0.8305, 0.1046, -0.1217]}
          userData={{ name: "detail_02" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_03.geometry}
          material={materials.Plastic_Green}
          position={[2.6628, 2.0262, 2.0896]}
          rotation={[0.9436, 0.1539, 1.2316]}
          userData={{ name: "detail_03" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_04.geometry}
          material={materials.Plastic_Red}
          position={[6.6854, -2.3012, 2.0957]}
          rotation={[2.5412, -0.4799, 0.7451]}
          userData={{ name: "detail_04" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_05.geometry}
          material={materials.plastic_white}
          position={[0.7175, 4.4445, 1.1391]}
          rotation={[3.0537, 1.0907, -1.9078]}
          userData={{ name: "detail_05" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_06.geometry}
          material={materials.Plastic_Black}
          position={[-2.0596, -1.9926, 2.387]}
          rotation={[0.4557, -0.1838, 1.7025]}
          userData={{ name: "detail_06" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_07.geometry}
          material={materials.plastic_transparent_blue}
          position={[4.6449, -1.8955, 3.2253]}
          rotation={[1.6207, -0.7656, 1.714]}
          userData={{ name: "detail_07" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_08.geometry}
          material={materials.Plastic_Black}
          position={[-2.7048, -0.8869, 0.9821]}
          rotation={[-Math.PI, 0, 1.5747]}
          userData={{ name: "detail_08" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_09.geometry}
          material={materials.rubber}
          position={[-6.5379, -12.3218, 1.228]}
          rotation={[-Math.PI, 0, -1.5669]}
          userData={{ name: "detail_09" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_10.geometry}
          material={materials.Plastic_Black}
          position={[-6.4479, 10.5776, 1.0064]}
          rotation={[0, 0, -1.5747]}
          userData={{ name: "detail_10" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_11.geometry}
          material={materials.rubber}
          position={[1.1357, 10.5479, 1.228]}
          rotation={[-Math.PI, 0, 1.5747]}
          userData={{ name: "detail_11" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_12.geometry}
          material={materials.Plastic_Black}
          position={[1.1325, 10.5479, 1.2289]}
          rotation={[-Math.PI, 0, 1.5747]}
          userData={{ name: "detail_12" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_13.geometry}
          material={materials.plastic_white}
          position={[1.1339, 10.5479, 1.2281]}
          rotation={[-Math.PI, 0, 1.5747]}
          userData={{ name: "detail_13" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_14.geometry}
          material={materials.Plastic_Opacity}
          position={[6.2658, 0.552, 0.7548]}
          rotation={[2.2858, 0.0005, 1.5685]}
          userData={{ name: "detail_14" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_15.geometry}
          material={materials.Plastic_Red}
          position={[2.4742, -4.564, 1.2414]}
          rotation={[-2.979, 0.286, 2.6105]}
          userData={{ name: "detail_15" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_16.geometry}
          material={materials.Plastic_Yellow}
          position={[-5.7815, 2.1077, 1.6103]}
          rotation={[3.1409, 0.002, 2.0169]}
          userData={{ name: "detail_16" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_17.geometry}
          material={materials.Plastic_Blue}
          position={[1.3321, 3.9595, 0.7258]}
          rotation={[0.0003, -0.0004, 1.6144]}
          userData={{ name: "detail_17" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_18.geometry}
          material={materials.plastic_orange}
          position={[-4.5451, -1.9871, 1.7029]}
          rotation={[0.2232, 0.2987, 1.6736]}
          userData={{ name: "detail_18" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_19.geometry}
          material={materials.Plastic_Blue}
          position={[-4.1302, 5.9276, 1.9844]}
          rotation={[-2.4146, 0.7833, -0.1993]}
          userData={{ name: "detail_19" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_20.geometry}
          material={materials.Plastic_Green}
          position={[-0.682, 3.472, 1.2338]}
          rotation={[0.0006, 0.4723, 3.1256]}
          userData={{ name: "detail_20" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_21.geometry}
          material={materials.plastic_orange}
          position={[-2.1777, 4.2534, 1.0545]}
          rotation={[0.9992, -0.8141, 1.1307]}
          userData={{ name: "detail_21" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_22.geometry}
          material={materials.plastic_transparent_turquoise}
          position={[-2.4435, 2.5149, 1.2179]}
          rotation={[1.2189, 0.1637, 1.6369]}
          userData={{ name: "detail_22" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_23.geometry}
          material={materials.plastic_gray}
          position={[-0.0546, 2.3437, 0.7257]}
          rotation={[-0.0004, 0.0008, 1.5678]}
          userData={{ name: "detail_23" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_24.geometry}
          material={materials.Plastic_Red}
          position={[3.9695, -2.546, 1.3655]}
          rotation={[-3.1415, -0.0004, 1.4406]}
          userData={{ name: "detail_24" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_25.geometry}
          material={materials.plastic_light_blue}
          position={[6.6384, 3.5957, 0.7555]}
          rotation={[2.2788, 0.0921, 1.4933]}
          userData={{ name: "detail_25" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_26.geometry}
          material={materials.Plastic_Yellow}
          position={[5.8333, -2.1001, 0.7701]}
          rotation={[0.8405, 0.2935, 1.8242]}
          userData={{ name: "detail_26" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_27.geometry}
          material={materials.Plastic_Black}
          position={[-2.2264, 0.1355, 1.2367]}
          rotation={[-0.8631, 0.0134, 1.5577]}
          userData={{ name: "detail_27" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_28.geometry}
          material={materials.rubber}
          position={[-5.868, 7.7308, -7.395]}
          rotation={[-0.8631, 0.0134, -1.5839]}
          userData={{ name: "detail_28" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_29.geometry}
          material={materials.Plastic_Black}
          position={[-6.1674, -6.9881, 10.1464]}
          rotation={[2.2784, -0.0134, -1.5577]}
          userData={{ name: "detail_29" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_30.geometry}
          material={materials.rubber}
          position={[1.4139, -7.2927, 10.0168]}
          rotation={[-0.8631, 0.0134, 1.5577]}
          userData={{ name: "detail_30" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_31.geometry}
          material={materials.Plastic_Black}
          position={[1.4139, -7.2927, 10.0168]}
          rotation={[-0.8631, 0.0134, 1.5577]}
          userData={{ name: "detail_31" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_33.geometry}
          material={materials.Plastic_Red}
          position={[1.9922, 2.1265, 0.7791]}
          rotation={[2.2519, 0.1057, -0.0943]}
          userData={{ name: "detail_33" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_34.geometry}
          material={materials.Plastic_Yellow}
          position={[4.4288, 2.8417, 0.8732]}
          rotation={[1.5647, 0.2012, 0.0003]}
          userData={{ name: "detail_34" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_35.geometry}
          material={materials.Plastic_Blue}
          position={[5.9819, 2.5105, 1.3476]}
          rotation={[2.9756, 0.1981, 0.1193]}
          userData={{ name: "detail_35" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_36.geometry}
          material={materials.Plastic_Green}
          position={[4.3429, -1.6116, 2.6239]}
          rotation={[-0.2114, 0.0202, -0.0781]}
          userData={{ name: "detail_36" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_37.geometry}
          material={materials.Plastic_Black}
          position={[-1.4473, 5.8874, 0.7698]}
          rotation={[2.5108, -0.2509, 0.3279]}
          userData={{ name: "detail_37" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_38.geometry}
          material={materials.Plastic_Yellow}
          position={[6.927, 0.9254, 1.957]}
          rotation={[-0.3624, -0.0265, -0.1246]}
          userData={{ name: "detail_38" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_39.geometry}
          material={materials.Plastic_Black}
          position={[7.23, 4.2849, 1.6194]}
          rotation={[-0.9399, 0.1179, -0.0856]}
          userData={{ name: "detail_39" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_40.geometry}
          material={materials.Plastic_Red}
          position={[6.597, 2.2213, 0.7359]}
          rotation={[2.7511, 0.0282, -0.0678]}
          userData={{ name: "detail_40" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_41.geometry}
          material={materials.Plastic_Opacity}
          position={[-6.6671, 3.0432, 1.4409]}
          rotation={[0, 0, -0.4391]}
          userData={{ name: "detail_41" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_42.geometry}
          material={materials.Plastic_Opacity}
          position={[3.7468, -4.8584, 1.9996]}
          rotation={[1.5723, 0.3074, 1.5692]}
          userData={{ name: "detail_42" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_43.geometry}
          material={materials.Plastic_Opacity}
          position={[-0.7207, -2.2133, 0.7943]}
          rotation={[2.5253, 0.5105, -2.0006]}
          userData={{ name: "detail_43" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_44.geometry}
          material={materials.Plastic_Green}
          position={[-1.4791, -3.5248, 0.8703]}
          rotation={[-1.5691, -0.9675, -0.0008]}
          userData={{ name: "detail_44" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_45.geometry}
          material={materials.Plastic_Red}
          position={[-3.1545, -2.4144, 0.8536]}
          rotation={[-1.5708, 0.1842, -Math.PI / 8]}
          userData={{ name: "detail_45" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_46.geometry}
          material={materials.Plastic_Black}
          position={[-3.4328, 2.9935, 0.7663]}
          rotation={[2.3445, 0.4938, 1.5351]}
          userData={{ name: "detail_46" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_47.geometry}
          material={materials.Plastic_Red}
          position={[1.6534, -2.6916, 1.0017]}
          rotation={[2.8117, 0.219, 1.0054]}
          userData={{ name: "detail_47" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_48.geometry}
          material={materials.Plastic_Black}
          position={[6.2914, -5.4406, 0.6509]}
          rotation={[-3.1416, 0, 2.9518]}
          userData={{ name: "detail_48" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_49.geometry}
          material={materials.Plastic_Green}
          position={[-4.2994, 5.1573, 1.68]}
          rotation={[0.0106, -0.2253, -0.2602]}
          userData={{ name: "detail_49" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_50.geometry}
          material={materials.Plastic_Red}
          position={[-1.599, -4.8627, 1.004]}
          rotation={[2.9637, 0.5161, 0.3495]}
          userData={{ name: "detail_50" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_51.geometry}
          material={materials.Plastic_Blue}
          position={[-1.6884, 1.1214, 2.73]}
          rotation={[-0.3783, 0.1616, -0.2466]}
          userData={{ name: "detail_51" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_52.geometry}
          material={materials.Plastic_Blue}
          position={[-5, 4.5677, 0.4476]}
          rotation={[-3.1292, 0.2376, -0.2108]}
          scale={[0.9954, 0.9954, 1]}
          userData={{ name: "detail_52" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_53.geometry}
          material={materials.Plastic_Opacity}
          position={[0.3565, 2.3164, 2.017]}
          rotation={[-0.0459, -1.0414, 0.1429]}
          userData={{ name: "detail_53" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_54.geometry}
          material={materials.plastic_transparent_turquoise}
          position={[6.3474, -0.4873, 2.1802]}
          rotation={[-1.594, 0.8532, -0.7855]}
          userData={{ name: "detail_54" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_55.geometry}
          material={materials.plastic_transparent_turquoise}
          position={[-1.8816, -2.73, 1.1936]}
          rotation={[2.0258, 0.4576, 1.7335]}
          userData={{ name: "detail_55" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_56.geometry}
          material={materials.plastic_transparent_turquoise}
          position={[3.0272, 4.0023, 1.7595]}
          rotation={[-0.0441, 1.2217, -0.3446]}
          userData={{ name: "detail_56" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_57.geometry}
          material={materials.plastic_transparent_red}
          position={[-0.9757, -0.8868, 1.081]}
          rotation={[-2.3644, -1.2956, -0.4502]}
          userData={{ name: "detail_57" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_58.geometry}
          material={materials.plastic_transparent_green}
          position={[3.3849, 1.2504, 2.5988]}
          rotation={[0.7318, 0.8428, 2.9971]}
          userData={{ name: "detail_58" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_59.geometry}
          material={materials.plastic_transparent_blue}
          position={[0.7809, 3.2438, 3.397]}
          rotation={[-0.8507, -1.5351, -0.6278]}
          userData={{ name: "detail_59" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_60.geometry}
          material={materials.plastic_transparent_red}
          position={[3.6836, 4.4836, 2.5426]}
          rotation={[1.3695, -0.1513, 1.1358]}
          userData={{ name: "detail_60" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_61.geometry}
          material={materials.plastic_gray}
          position={[-19.2201, -78.8214, -0.001]}
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: "detail_61" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_62.geometry}
          material={materials.plastic_white}
          position={[1.5381, -7.2556, 10.0134]}
          rotation={[-0.8632, 0.003, 1.5683]}
          userData={{ name: "detail_62" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_63.geometry}
          material={materials.plastic_white}
          position={[-6.0477, -7.0077, 10.1673]}
          rotation={[2.2784, -0.0134, -1.5683]}
          userData={{ name: "detail_63" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_64.geometry}
          material={materials.plastic_white}
          position={[-6.448, 10.5776, 0.9798]}
          rotation={[0, -0.0104, -1.5747]}
          userData={{ name: "detail_64" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_65.geometry}
          material={materials.Plastic_Opacity}
          position={[-1.2798, 4.6878, 1.5979]}
          userData={{ name: "detail_65" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Random_Lego_Bricks.gltf");